#!/bin/sh
# angelus - John Burnett & Will Johnson (c)
# Script for executing Angelus
# 
# Usage:
# Place WAV files in audio folder
# Pass 1 or more names of the files to be analyzed or "-a" for all files
# Analysis files will be written to the build and synthesis folders
# 
# Example:
# $./angelus file1.wav file2.wav file3.wav

if [ $# -eq 0 ]; then
    echo "Please provide file to analyze."
elif [ $1="-a" ]; then
    cd audio
    files=`find *`
    cd ../src
    for file in $files; do
        python angelus.py $file
        echo
    done
else
    cd src
    for ARG in $*; do
        python angelus.py $ARG
        echo
    done
fi
